-- +goose Up
CREATE TABLE account (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `email` TEXT NOT NULL UNIQUE,
    `password` TEXT NOT NULL,
    `last` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Last login time
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `locked` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `verified` BOOLEAN NOT NULL DEFAULT FALSE,
    `totp` BOOLEAN NOT NULL DEFAULT FALSE,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE account;